services:
  - type: web
    name: server-resume
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: PORT
        value: "5001"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JOOBLE_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
